server {
    listen 80;
    listen [::]:80;
    server_name mirrors.5cena.cc;
    root /srv/sl7-apt/public;
    location /.well-known/acme-challenge/ { try_files $uri =404; }
    location / { try_files $uri $uri/ =404; }
}
