server {
    listen 80;
    listen [::]:80;
    server_name mirrors.5cena.cc;
    root /srv/mirrors;
    location /.well-known/acme-challenge/ {
        root /srv/sl7-apt/public;
        try_files $uri =404;
    }
    location /sl7/ { autoindex on; try_files $uri $uri/ =404; }
    location / { try_files $uri $uri/ =404; }
}
